name: ATtiny85APU assembly

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Assemble for the ATtiny${{ matrix.platform.attiny }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - {attiny: 25}
          - {attiny: 45}
          - {attiny: 85}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache avra
        uses: ./.github/actions/cache_avra
      - name: Set path
        run: |
          echo "${{ github.workspace }}/opt/avra/bin" >> $GITHUB_PATH
      - name: Build the firmware
        run: make ATTINY=${{ matrix.platform.attiny }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: attiny85apu_t${{ matrix.platform.attiny }}.hex
          path: bin/avr/main.hex
 